name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          Import-Module -Name PSScriptAnalyzer, ./.tests/ScriptAnalyzer.Sarif
          $Sarif = Invoke-ScriptAnalyzer -Path . -Recurse -Settings .tests/CodeFormatting.psd1 |
            Sort-Object -Property ScriptPath, Line, Severity, RuleName, Message | ConvertTo-Sarif
          $Sarif | ConvertTo-Json -Depth 100 -Compress | Set-Content results.sarif
          $Sarif | Show-GitHubAnnotation -Path .

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif
